services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - api_network

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    networks:
      - api_network
    depends_on:
      - backend

networks:
  api_network:
    driver: bridge
